<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="12" failed="2" total="18" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Practice regression" duration-ms="26047" started-at="2022-07-30T17:03:40Z" finished-at="2022-07-30T17:04:06Z">
    <groups>
    </groups>
    <test name="Test case 1" duration-ms="20562" started-at="2022-07-30T17:03:40Z" finished-at="2022-07-30T17:04:00Z">
      <class name="com.tours.tests.RegistrationPageTest">
        <test-method status="PASS" signature="initializePage(java.lang.String)[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d]" name="initializePage" is-config="true" duration-ms="8324" started-at="2022-07-30T22:33:40Z" finished-at="2022-07-30T22:33:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializePage -->
        <test-method status="FAIL" signature="enterContactInformation()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d]" name="enterContactInformation" duration-ms="10391" started-at="2022-07-30T22:33:48Z" finished-at="2022-07-30T22:33:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected condition failed: waiting for com.tours.pages.main.ContactInformation$$Lambda$351/1854889945@447567 (tried for 10 second(s) with 500 milliseconds interval)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected condition failed: waiting for com.tours.pages.main.ContactInformation$$Lambda$351/1854889945@447567 (tried for 10 second(s) with 500 milliseconds interval)
	at org.testng.Assert.fail(Assert.java:94)
	at com.tours.tests.RegistrationPageTest.enterContactInformation(RegistrationPageTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterContactInformation -->
        <test-method status="PASS" signature="enterMailingInformation()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d]" name="enterMailingInformation" duration-ms="406" started-at="2022-07-30T22:33:59Z" finished-at="2022-07-30T22:33:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterMailingInformation -->
        <test-method status="PASS" signature="enterUserInformation()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d]" name="enterUserInformation" duration-ms="236" started-at="2022-07-30T22:33:59Z" finished-at="2022-07-30T22:33:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterUserInformation -->
        <test-method status="SKIP" signature="enterSubmit()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d]" name="enterSubmit" duration-ms="0" started-at="2022-07-30T22:33:59Z" depends-on-methods="com.tours.tests.RegistrationPageTest.enterUserInformation, com.tours.tests.RegistrationPageTest.enterContactInformation, com.tours.tests.RegistrationPageTest.enterMailingInformation" finished-at="2022-07-30T22:33:59Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RegistrationPageTest.enterSubmit()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RegistrationPageTest.enterSubmit()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterSubmit -->
        <test-method status="SKIP" signature="confirmregistrationTest()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d]" name="confirmregistrationTest" duration-ms="0" started-at="2022-07-30T22:33:59Z" depends-on-methods="com.tours.tests.RegistrationPageTest.enterSubmit" finished-at="2022-07-30T22:33:59Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RegistrationPageTest.confirmregistrationTest()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RegistrationPageTest.confirmregistrationTest()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- confirmregistrationTest -->
        <test-method status="SKIP" signature="enterFlightDetails()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d]" name="enterFlightDetails" duration-ms="0" started-at="2022-07-30T22:33:59Z" depends-on-methods="com.tours.tests.RegistrationPageTest.confirmregistrationTest" finished-at="2022-07-30T22:33:59Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RegistrationPageTest.enterFlightDetails()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RegistrationPageTest.enterFlightDetails()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterFlightDetails -->
        <test-method status="SKIP" signature="enterBillingAddress()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d]" name="enterBillingAddress" duration-ms="0" started-at="2022-07-30T22:33:59Z" depends-on-methods="com.tours.tests.RegistrationPageTest.selectDepartureandReturn" finished-at="2022-07-30T22:33:59Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RegistrationPageTest.enterBillingAddress()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RegistrationPageTest.enterBillingAddress()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterBillingAddress -->
        <test-method status="SKIP" signature="selectDepartureandReturn()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d]" name="selectDepartureandReturn" duration-ms="0" started-at="2022-07-30T22:33:59Z" depends-on-methods="com.tours.tests.RegistrationPageTest.enterFlightDetails" finished-at="2022-07-30T22:33:59Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RegistrationPageTest.selectDepartureandReturn()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RegistrationPageTest.selectDepartureandReturn()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectDepartureandReturn -->
        <test-method status="SKIP" signature="FightconfirmationDetails()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d]" name="FightconfirmationDetails" duration-ms="0" started-at="2022-07-30T22:33:59Z" depends-on-methods="com.tours.tests.RegistrationPageTest.enterBillingAddress" finished-at="2022-07-30T22:33:59Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RegistrationPageTest.FightconfirmationDetails()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RegistrationPageTest.FightconfirmationDetails()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FightconfirmationDetails -->
        <test-method status="PASS" signature="close()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d]" name="close" is-config="true" duration-ms="659" started-at="2022-07-30T22:33:59Z" finished-at="2022-07-30T22:34:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- com.tours.tests.RegistrationPageTest -->
    </test> <!-- Test case 1 -->
    <test name="Test case 2" duration-ms="26047" started-at="2022-07-30T17:03:40Z" finished-at="2022-07-30T17:04:06Z">
      <class name="com.tours.tests.RegistrationPageTest">
        <test-method status="PASS" signature="initializePage(java.lang.String)[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5]" name="initializePage" is-config="true" duration-ms="13955" started-at="2022-07-30T22:33:40Z" finished-at="2022-07-30T22:33:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializePage -->
        <test-method status="FAIL" signature="enterContactInformation()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5]" name="enterContactInformation" duration-ms="10357" started-at="2022-07-30T22:33:54Z" finished-at="2022-07-30T22:34:04Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected condition failed: waiting for com.tours.pages.main.ContactInformation$$Lambda$351/1854889945@31ff51ec (tried for 10 second(s) with 500 milliseconds interval)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected condition failed: waiting for com.tours.pages.main.ContactInformation$$Lambda$351/1854889945@31ff51ec (tried for 10 second(s) with 500 milliseconds interval)
	at org.testng.Assert.fail(Assert.java:94)
	at com.tours.tests.RegistrationPageTest.enterContactInformation(RegistrationPageTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterContactInformation -->
        <test-method status="PASS" signature="enterMailingInformation()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5]" name="enterMailingInformation" duration-ms="409" started-at="2022-07-30T22:34:04Z" finished-at="2022-07-30T22:34:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterMailingInformation -->
        <test-method status="PASS" signature="enterUserInformation()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5]" name="enterUserInformation" duration-ms="87" started-at="2022-07-30T22:34:05Z" finished-at="2022-07-30T22:34:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterUserInformation -->
        <test-method status="SKIP" signature="confirmregistrationTest()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5]" name="confirmregistrationTest" duration-ms="0" started-at="2022-07-30T22:34:05Z" depends-on-methods="com.tours.tests.RegistrationPageTest.enterSubmit" finished-at="2022-07-30T22:34:05Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RegistrationPageTest.confirmregistrationTest()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RegistrationPageTest.confirmregistrationTest()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- confirmregistrationTest -->
        <test-method status="SKIP" signature="enterSubmit()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5]" name="enterSubmit" duration-ms="0" started-at="2022-07-30T22:34:05Z" depends-on-methods="com.tours.tests.RegistrationPageTest.enterUserInformation, com.tours.tests.RegistrationPageTest.enterContactInformation, com.tours.tests.RegistrationPageTest.enterMailingInformation" finished-at="2022-07-30T22:34:05Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RegistrationPageTest.enterSubmit()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RegistrationPageTest.enterSubmit()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterSubmit -->
        <test-method status="SKIP" signature="enterFlightDetails()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5]" name="enterFlightDetails" duration-ms="0" started-at="2022-07-30T22:34:05Z" depends-on-methods="com.tours.tests.RegistrationPageTest.confirmregistrationTest" finished-at="2022-07-30T22:34:05Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RegistrationPageTest.enterFlightDetails()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RegistrationPageTest.enterFlightDetails()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterFlightDetails -->
        <test-method status="SKIP" signature="selectDepartureandReturn()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5]" name="selectDepartureandReturn" duration-ms="0" started-at="2022-07-30T22:34:05Z" depends-on-methods="com.tours.tests.RegistrationPageTest.enterFlightDetails" finished-at="2022-07-30T22:34:05Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RegistrationPageTest.selectDepartureandReturn()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RegistrationPageTest.selectDepartureandReturn()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectDepartureandReturn -->
        <test-method status="PASS" signature="close()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5]" name="close" is-config="true" duration-ms="847" started-at="2022-07-30T22:34:05Z" finished-at="2022-07-30T22:34:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method status="SKIP" signature="FightconfirmationDetails()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5]" name="FightconfirmationDetails" duration-ms="0" started-at="2022-07-30T22:34:05Z" depends-on-methods="com.tours.tests.RegistrationPageTest.enterBillingAddress" finished-at="2022-07-30T22:34:05Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RegistrationPageTest.FightconfirmationDetails()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RegistrationPageTest.FightconfirmationDetails()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FightconfirmationDetails -->
        <test-method status="SKIP" signature="enterBillingAddress()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5]" name="enterBillingAddress" duration-ms="0" started-at="2022-07-30T22:34:05Z" depends-on-methods="com.tours.tests.RegistrationPageTest.selectDepartureandReturn" finished-at="2022-07-30T22:34:05Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method RegistrationPageTest.enterBillingAddress()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method RegistrationPageTest.enterBillingAddress()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enterBillingAddress -->
      </class> <!-- com.tours.tests.RegistrationPageTest -->
    </test> <!-- Test case 2 -->
  </suite> <!-- Practice regression -->
</testng-results>
