<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MOASIIL" name="com.tours.tests.RegistrationPageTest" tests="18" failures="2" timestamp="30 Jul 2022 17:04:06 GMT" time="21.886" errors="12">
  <testcase name="enterFlightDetails" time="0.000" classname="com.tours.tests.RegistrationPageTest">
    <error type="java.lang.Throwable" message="Method RegistrationPageTest.enterFlightDetails()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegistrationPageTest.enterFlightDetails()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- enterFlightDetails -->
  <testcase name="enterBillingAddress" time="0.000" classname="com.tours.tests.RegistrationPageTest">
    <error type="java.lang.Throwable" message="Method RegistrationPageTest.enterBillingAddress()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegistrationPageTest.enterBillingAddress()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- enterBillingAddress -->
  <testcase name="selectDepartureandReturn" time="0.000" classname="com.tours.tests.RegistrationPageTest">
    <error type="java.lang.Throwable" message="Method RegistrationPageTest.selectDepartureandReturn()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegistrationPageTest.selectDepartureandReturn()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- selectDepartureandReturn -->
  <testcase name="enterMailingInformation" time="0.406" classname="com.tours.tests.RegistrationPageTest"/>
  <testcase name="FightconfirmationDetails" time="0.000" classname="com.tours.tests.RegistrationPageTest">
    <error type="java.lang.Throwable" message="Method RegistrationPageTest.FightconfirmationDetails()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegistrationPageTest.FightconfirmationDetails()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- FightconfirmationDetails -->
  <testcase name="confirmregistrationTest" time="0.000" classname="com.tours.tests.RegistrationPageTest">
    <error type="java.lang.Throwable" message="Method RegistrationPageTest.confirmregistrationTest()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegistrationPageTest.confirmregistrationTest()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- confirmregistrationTest -->
  <testcase name="enterMailingInformation" time="0.409" classname="com.tours.tests.RegistrationPageTest"/>
  <testcase name="enterSubmit" time="0.000" classname="com.tours.tests.RegistrationPageTest">
    <error type="java.lang.Throwable" message="Method RegistrationPageTest.enterSubmit()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegistrationPageTest.enterSubmit()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- enterSubmit -->
  <testcase name="enterContactInformation" time="10.391" classname="com.tours.tests.RegistrationPageTest">
    <failure type="java.lang.AssertionError" message="Expected condition failed: waiting for com.tours.pages.main.ContactInformation$$Lambda$351/1854889945@447567 (tried for 10 second(s) with 500 milliseconds interval)">
      <![CDATA[java.lang.AssertionError: Expected condition failed: waiting for com.tours.pages.main.ContactInformation$$Lambda$351/1854889945@447567 (tried for 10 second(s) with 500 milliseconds interval)
	at org.testng.Assert.fail(Assert.java:94)
	at com.tours.tests.RegistrationPageTest.enterContactInformation(RegistrationPageTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- enterContactInformation -->
  <testcase name="confirmregistrationTest" time="0.000" classname="com.tours.tests.RegistrationPageTest">
    <error type="java.lang.Throwable" message="Method RegistrationPageTest.confirmregistrationTest()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegistrationPageTest.confirmregistrationTest()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- confirmregistrationTest -->
  <testcase name="enterFlightDetails" time="0.000" classname="com.tours.tests.RegistrationPageTest">
    <error type="java.lang.Throwable" message="Method RegistrationPageTest.enterFlightDetails()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegistrationPageTest.enterFlightDetails()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- enterFlightDetails -->
  <testcase name="enterUserInformation" time="0.087" classname="com.tours.tests.RegistrationPageTest"/>
  <testcase name="selectDepartureandReturn" time="0.000" classname="com.tours.tests.RegistrationPageTest">
    <error type="java.lang.Throwable" message="Method RegistrationPageTest.selectDepartureandReturn()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegistrationPageTest.selectDepartureandReturn()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- selectDepartureandReturn -->
  <testcase name="FightconfirmationDetails" time="0.000" classname="com.tours.tests.RegistrationPageTest">
    <error type="java.lang.Throwable" message="Method RegistrationPageTest.FightconfirmationDetails()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegistrationPageTest.FightconfirmationDetails()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- FightconfirmationDetails -->
  <testcase name="enterSubmit" time="0.000" classname="com.tours.tests.RegistrationPageTest">
    <error type="java.lang.Throwable" message="Method RegistrationPageTest.enterSubmit()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegistrationPageTest.enterSubmit()[pri:0, instance:com.tours.tests.RegistrationPageTest@a74868d] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- enterSubmit -->
  <testcase name="enterBillingAddress" time="0.000" classname="com.tours.tests.RegistrationPageTest">
    <error type="java.lang.Throwable" message="Method RegistrationPageTest.enterBillingAddress()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method RegistrationPageTest.enterBillingAddress()[pri:0, instance:com.tours.tests.RegistrationPageTest@47db50c5] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- enterBillingAddress -->
  <testcase name="enterContactInformation" time="10.357" classname="com.tours.tests.RegistrationPageTest">
    <failure type="java.lang.AssertionError" message="Expected condition failed: waiting for com.tours.pages.main.ContactInformation$$Lambda$351/1854889945@31ff51ec (tried for 10 second(s) with 500 milliseconds interval)">
      <![CDATA[java.lang.AssertionError: Expected condition failed: waiting for com.tours.pages.main.ContactInformation$$Lambda$351/1854889945@31ff51ec (tried for 10 second(s) with 500 milliseconds interval)
	at org.testng.Assert.fail(Assert.java:94)
	at com.tours.tests.RegistrationPageTest.enterContactInformation(RegistrationPageTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- enterContactInformation -->
  <testcase name="enterUserInformation" time="0.236" classname="com.tours.tests.RegistrationPageTest"/>
</testsuite> <!-- com.tours.tests.RegistrationPageTest -->
